---
title: "Exercise Measure Development PCA"
date: "`r format(Sys.time(), '%m/%d/%y')`"
output: 
  html_document: 
    theme: yeti 
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
.libPaths(Sys.getenv("R_LIBS_USER"))

knitr::opts_chunk$set(echo = TRUE)

# detach all libraries

detachAllPackages <- function() {
  basic.packages <- c("package:stats", "package:graphics", "package:grDevices", "package:utils", "package:datasets", "package:methods", "package:base")
  package.list <- search()[ifelse(unlist(gregexpr("package:", search()))==1, TRUE, FALSE)]
  package.list <- setdiff(package.list, basic.packages)
  if (length(package.list)>0)  for (package in package.list) detach(package,  character.only=TRUE)
}
detachAllPackages()

# function to load libraries

pkgTest <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[,  "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg,  dependencies = TRUE)
  sapply(pkg,  require,  character.only = TRUE)
}

# knitr

knitr::knit_hooks$set(output = function(x, options){
  if(!is.null(options$max_height)){
    paste('<pre style = "max-height:', options$max_height, '; float: left; width: 910px; overflow-y: auto;">', x, "</pre>", sep = "")
  }else{
    x
  }
  
})

# loading packages 
lapply(c("tidyverse"),pkgTest)
lapply(c("readr"),pkgTest)
lapply(c("paletteer"),pkgTest)
lapply(c("kableExtra"),pkgTest)
library(tidyverse)
library(readr)
library(paletteer)
library(kableExtra)
```

```{r, include=FALSE}
options(width = 60)
local({
  hook_output <- knitr::knit_hooks$get('output')
  knitr::knit_hooks$set(output = function(x, options) {
    if (!is.null(options$max.height)) options$attr.output <- c(
      options$attr.output,
      sprintf('style="max-height: %s;"', options$max.height)
    )
    hook_output(x, options)
  })
})
```

```{css, echo=FALSE}
<style type="text/css">

body, td {
   font-size: 14px;
}
code.r{
  font-size: 12px;
}
pre {
  font-size: 12px
}
</style>
```

```{css, echo=FALSE}
  #TOC {
    max-width: fit-content;
    white-space: nowrap;
  }
  
  div:has(> #TOC) {
    display: flex;
    flex-direction: row-reverse;
}
```

### Importing Data  

```{r, warning=FALSE, message=FALSE}
# setwd("/Users/kdlee/Desktop/MIAU-exer-FA/data")

setwd("/Users/carolinelee/Desktop/MIAU-exer-FA/data")

# setwd("/Users/48909138/OneDrive - Southern Methodist University/Desktop/MIAU-exer-FA/data")

Community_Overall <- read_csv("Com_Overall_FA.csv")

Community_Positive <- read_csv("Com_Pos_FA.csv")

Community_Negative <- read_csv("Com_Neg_FA.csv")

MTurk_Overall <- read_csv("MTurk_Overall_FA.csv")

MTurk_Positive <- read_csv("MTurk_Pos_FA.csv")

MTurk_Negative <- read_csv("MTurk_Neg_FA.csv")

SMU_Overall <- read_csv("SMU_Overall_FA.csv")

SMU_Positive <- read_csv("SMU_Pos_FA.csv")

SMU_Negative <- read_csv("SMU_Neg_FA.csv")
```

### Compiling Data 

```{r, results='asis'}
Merge1 <- merge(Community_Overall, Community_Positive, by = "Item_No", all.x = TRUE)

Merge2 <- merge(Merge1, Community_Negative, by = "Item_No", all.x = TRUE)

Merge3 <- merge(Merge2, MTurk_Overall, by = "Item_No", all.x = TRUE)

Merge4 <- merge(Merge3, MTurk_Positive, by = "Item_No", all.x = TRUE)

Merge5 <- merge(Merge4, MTurk_Negative, by = "Item_No", all.x = TRUE)

Merge6 <- merge(Merge5, SMU_Overall, by = "Item_No", all.x = TRUE)

Merge7 <- merge(Merge6, SMU_Positive, by = "Item_No", all.x = TRUE)

Final_DF <- merge(Merge7, SMU_Negative, by = "Item_No", all.x = TRUE)
```

```{r}
Final_DF_NoNum <- Final_DF[,-1]

Final_DF$LoadedFactor <- apply(Final_DF_NoNum, 1, function(i) paste(colnames(Final_DF_NoNum)[!is.na(i) ], collapse = ", "))

function1 <- function(x) {
  count.fields(textConnection(Final_DF$LoadedFactor[x]), sep = ",", blank.lines.skip = FALSE)
}

tbl1 <- as.data.frame(table(function1(1:312)))

knitr::kable(tbl1)
```

```{r}
FL_count <- as.list(function1(1:312)) # number of factor loadings per item 

### ZERO FACTOR LOADINGS ###

# red list, items that did not load on any factor =========================== RED 1 START

zeroFL_items <- which(FL_count == 0)

# =========================================================================== RED 1 END

### ONE FACTOR LOADING ###

# red list, items that only loaded on one factor =========================== RED 2 START

oneFL_items <- which(FL_count == 1)

# =========================================================================== RED 2 END

### TWO FACTOR LOADINGS 

twoFL_items <- which(FL_count == 2) # subsetting for items that loaded on two factors

twoFL_df <- Final_DF[twoFL_items, ]

tbl2 <- as.data.frame(table(twoFL_df$LoadedFactor))

knitr::kable(tbl2)
```

```{r}
twoFL_notsplit_df <- with(twoFL_df, which(LoadedFactor %in% c("Com_Neg_F2_NegApp, SMU_Overall_F4_NegApp", "Com_Neg_F5_NegApp_Prelim, SMU_Overall_F4_NegApp", "Com_Pos_F1_Cog, SMU_Pos_F1_Cog", "Com_Pos_F4_Flow, SMU_Overall_F8_Flow", "MTurk_Neg_F2_NegHealth, SMU_Neg_F5_NegHealth_Prelim", "MTurk_Overall_F7_Flow, SMU_Overall_F8_Flow")))

twoFL_notsplit_df <- twoFL_df[twoFL_notsplit_df, ]

twoFL_notsplit_NoNum <- twoFL_notsplit_df[,-c(1, 49)] # removing non-numerical columns

twoFL_notsplit_df$firstloading <- apply(twoFL_notsplit_NoNum, 1, function(z) na.omit(z)[1]) # extract first loading 

twoFL_notsplit_df$firstloading <- as.numeric(twoFL_notsplit_df$firstloading)

twoFL_notsplit_df$secondloading <- apply(twoFL_notsplit_NoNum, 1, function(z) na.omit(z)[2]) # extract second loading 

twoFL_notsplit_df$secondloading <- as.numeric(twoFL_notsplit_df$secondloading)

twoFL_notsplit_df$firstFL_inrange <- ifelse(abs(twoFL_notsplit_df$firstloading) >= .40, TRUE, FALSE)

twoFL_notsplit_df$secondFL_inrange <- ifelse(abs(twoFL_notsplit_df$secondloading) >= .40, TRUE, FALSE)

twoFL_notsplit_df$category <- ifelse(twoFL_notsplit_df$firstFL_inrange == TRUE & twoFL_notsplit_df$secondFL_inrange == TRUE, "YELLOW", "RED")

# items that loaded in range in two different samples for the same factor ======== YELLOW 1 START

twoFL_YELLOW <- with(twoFL_notsplit_df, which(category %in% "YELLOW"))

twoFL_YELLOW <- twoFL_notsplit_df[twoFL_YELLOW, ]

twoFL_YELLOW_items <- twoFL_YELLOW$Item_No 

# ========================================================================= YELLOW 1 END 

# non-split items that were in range in only one or out of range in both == RED 3 START

twoFL_RED_notsplit <- with(twoFL_notsplit_df, which(category %in% "RED"))

twoFL_RED_notsplit <- twoFL_notsplit_df[twoFL_RED_notsplit, ]

twoFL_RED_notsplit_items <- twoFL_RED_notsplit$Item_No 

# ========================================================================= RED 3 END 

# split items ============================================================= RED 4 START
twoFL_split_df <- with(twoFL_df, which(LoadedFactor %in% c("Com_Neg_F1_Time, MTurk_Neg_F5_Pain", "Com_Overall_F7_Soc, MTurk_Overall_F4_PosApp", "Com_Pos_F1_Cog, Com_Pos_F2_Pride", "Com_Pos_F7_Flow_Prelim, SMU_Overall_F5_Prog", "MTurk_Overall_F4_PosApp, SMU_Neg_F1_Time")))

twoFL_split_df <- twoFL_df[twoFL_split_df, ]

twoFL_RED_split_items <- twoFL_split_df$Item_No

# ========================================================================= RED 4 END

### THREE FACTOR LOADINGS 

threeFL_df <- which(FL_count == 3) # subsetting for items that loaded on three factors

threeFL_df <- Final_DF[threeFL_df, ]

tbl3 <- as.data.frame(table(threeFL_df$LoadedFactor))

knitr::kable(tbl3)
```

```{r}
threeFL_notsplit_df <- with(threeFL_df, which(LoadedFactor %in% c("Com_Neg_F1_Time, MTurk_Neg_F4_Time, SMU_Neg_F1_Time", "Com_Neg_F2_NegApp, MTurk_Neg_F1_NegApp, SMU_Overall_F4_NegApp", "Com_Neg_F4_Flow_Prelim, MTurk_Overall_F7_Flow, SMU_Overall_F8_Flow", "Com_Overall_F4_Pain, MTurk_Neg_F3_Pain, SMU_Neg_F4_Pain", "Com_Overall_F4_Pain, MTurk_Neg_F3_Pain, SMU_Neg_F6_Pain", "Com_Overall_F4_Pain, MTurk_Neg_F5_Pain, SMU_Neg_F6_Pain", "Com_Overall_F5_Prog, MTurk_Overall_F5_Prog, SMU_Overall_F5_Prog", "Com_Overall_F6_PosApp, MTurk_Overall_F4_PosApp, SMU_Overall_F6_PosApp", "Com_Pos_F1_Cog, MTurk_Overall_F3_Cog, SMU_Pos_F1_Cog", "Com_Pos_F2_Pride, MTurk_Pos_F1_Pride, SMU_Pos_F3_Pride", "Com_Pos_F3_Phys, MTurk_Pos_F2_Phys, SMU_Pos_F2_Phys", "Com_Pos_F3_Phys, MTurk_Pos_F3_Phys, SMU_Pos_F2_Phys", "Com_Pos_F4_Flow, MTurk_Overall_F7_Flow, SMU_Overall_F8_Flow")))

threeFL_notsplit_df <- threeFL_df[threeFL_notsplit_df, ]

threeFL_notsplit_NoNum <- threeFL_notsplit_df[,-c(1, 49)] # removing non-numerical columns

threeFL_notsplit_df$firstloading <- apply(threeFL_notsplit_NoNum, 1, function(z) na.omit(z)[1]) # extract first loading 

threeFL_notsplit_df$firstloading <- as.numeric(threeFL_notsplit_df$firstloading)

threeFL_notsplit_df$secondloading <- apply(threeFL_notsplit_NoNum, 1, function(z) na.omit(z)[2]) # extract second loading 

threeFL_notsplit_df$secondloading <- as.numeric(threeFL_notsplit_df$secondloading)

threeFL_notsplit_df$thirdloading <- apply(threeFL_notsplit_NoNum, 1, function(z) na.omit(z)[3]) # extract third loading 

threeFL_notsplit_df$thirdloading <- as.numeric(threeFL_notsplit_df$thirdloading)

threeFL_notsplit_df$firstFL_inrange <- ifelse(abs(threeFL_notsplit_df$firstloading) >= .40, TRUE, FALSE)

threeFL_notsplit_df$secondFL_inrange <- ifelse(abs(threeFL_notsplit_df$secondloading) >= .40, TRUE, FALSE)

threeFL_notsplit_df$thirdFL_inrange <- ifelse(abs(threeFL_notsplit_df$thirdloading) >= .40, TRUE, FALSE)

threeFL_notsplit_df$category <- ifelse(threeFL_notsplit_df$firstFL_inrange == TRUE & threeFL_notsplit_df$secondFL_inrange == TRUE & threeFL_notsplit_df$thirdFL_inrange == TRUE, "GREEN", "NOT_GREEN")

# items that loaded in range for the same factor across all three samples ====================== GREEN 1 START

threeFL_GREEN <- with(threeFL_notsplit_df, which(category %in% "GREEN"))

threeFL_GREEN <- threeFL_notsplit_df[threeFL_GREEN, ]

threeFL_GREEN_items <- threeFL_GREEN$Item_No  

# ============================================================================================== GREEN 1 END 

threeFL_NOTGREEN <- with(threeFL_notsplit_df, which(category %in% "NOT_GREEN"))

threeFL_NOTGREEN <- threeFL_notsplit_df[threeFL_NOTGREEN, ]

threeFL_NOTGREEN_loadings <- threeFL_NOTGREEN[,49:55]
```

```{r}
threeFL_NOTGREEN_row1 <- as.data.frame(threeFL_NOTGREEN_loadings[1,])

knitr::kable(threeFL_NOTGREEN_row1) # good in 2/3, yellow
```

```{r}
threeFL_NOTGREEN_row2 <- as.data.frame(threeFL_NOTGREEN_loadings[2,])

knitr::kable(threeFL_NOTGREEN_row2) # good in 2/3, yellow
```

```{r}
threeFL_NOTGREEN_row3 <- as.data.frame(threeFL_NOTGREEN_loadings[3,])

knitr::kable(threeFL_NOTGREEN_row3) # good in 2/3, yellow
```

```{r}
threeFL_NOTGREEN_row4 <- as.data.frame(threeFL_NOTGREEN_loadings[4,])

knitr::kable(threeFL_NOTGREEN_row4) # good in 2/3, yellow
```

```{r}
threeFL_NOTGREEN_row5 <- as.data.frame(threeFL_NOTGREEN_loadings[5,])

knitr::kable(threeFL_NOTGREEN_row5) # only good in 1 sample, red
```

```{r}
threeFL_NOTGREEN_row6 <- as.data.frame(threeFL_NOTGREEN_loadings[6,])

knitr::kable(threeFL_NOTGREEN_row6) # only good in 1 sample, red
```

```{r}
threeFL_NOTGREEN_row7 <- as.data.frame(threeFL_NOTGREEN_loadings[7,])

knitr::kable(threeFL_NOTGREEN_row7) # only good in 1 sample, red
```

```{r}
# ========================================================================== YELLOW 2 START 

threeFL_YELLOW_notsplit <- threeFL_NOTGREEN[c(1:4),]

threeFL_YELLOW_notsplit_items <- threeFL_YELLOW_notsplit$Item_No

# =========================================================================== YELLOW 2 END  

# ========================================================================== RED 5 START 

threeFL_RED_notsplit <- threeFL_NOTGREEN[c(5:7),]

threeFL_RED_notsplit_items <- threeFL_RED_notsplit$Item_No
# ========================================================================== RED 5 END 

```

```{r}
threeFL_split_df <- with(threeFL_df, which(!LoadedFactor %in% c("Com_Neg_F1_Time, MTurk_Neg_F4_Time, SMU_Neg_F1_Time", "Com_Neg_F2_NegApp, MTurk_Neg_F1_NegApp, SMU_Overall_F4_NegApp", "Com_Neg_F4_Flow_Prelim, MTurk_Overall_F7_Flow, SMU_Overall_F8_Flow", "Com_Overall_F4_Pain, MTurk_Neg_F3_Pain, SMU_Neg_F4_Pain", "Com_Overall_F4_Pain, MTurk_Neg_F3_Pain, SMU_Neg_F6_Pain", "Com_Overall_F4_Pain, MTurk_Neg_F5_Pain, SMU_Neg_F6_Pain", "Com_Overall_F5_Prog, MTurk_Overall_F5_Prog, SMU_Overall_F5_Prog", "Com_Overall_F6_PosApp, MTurk_Overall_F4_PosApp, SMU_Overall_F6_PosApp", "Com_Pos_F1_Cog, MTurk_Overall_F3_Cog, SMU_Pos_F1_Cog", "Com_Pos_F2_Pride, MTurk_Pos_F1_Pride, SMU_Pos_F3_Pride", "Com_Pos_F3_Phys, MTurk_Pos_F2_Phys, SMU_Pos_F2_Phys", "Com_Pos_F3_Phys, MTurk_Pos_F3_Phys, SMU_Pos_F2_Phys" ,"Com_Pos_F4_Flow, MTurk_Overall_F7_Flow, SMU_Overall_F8_Flow")))

threeFL_split_df <- threeFL_df[threeFL_split_df, ]

threeFL_split_NoNum <- threeFL_split_df[,-c(1, 49)] # removing non-numerical columns

threeFL_split_df$firstloading <- apply(threeFL_split_NoNum, 1, function(z) na.omit(z)[1]) # extract first loading 

threeFL_split_df$firstloading <- as.numeric(threeFL_split_df$firstloading)

threeFL_split_df$secondloading <- apply(threeFL_split_NoNum, 1, function(z) na.omit(z)[2]) # extract second loading 

threeFL_split_df$secondloading <- as.numeric(threeFL_split_df$secondloading)

threeFL_split_df$thirdloading <- apply(threeFL_split_NoNum, 1, function(z) na.omit(z)[3]) # extract third loading 

threeFL_split_df$thirdloading <- as.numeric(threeFL_split_df$thirdloading)

threeFL_split_df$firstFL_inrange <- ifelse(abs(threeFL_split_df$firstloading) >= .40, TRUE, FALSE)

threeFL_split_df$secondFL_inrange <- ifelse(abs(threeFL_split_df$secondloading) >= .40, TRUE, FALSE)

threeFL_split_df$thirdFL_inrange <- ifelse(abs(threeFL_split_df$thirdloading) >= .40, TRUE, FALSE)

threeFL_split_loadings <- threeFL_split_df[,49:55]
```

```{r}
threeFL_split_row1 <- as.data.frame(threeFL_split_loadings[1,])

knitr::kable(threeFL_split_row1) # cross-loading >.30, RED
```

```{r}
threeFL_split_row2 <- as.data.frame(threeFL_split_loadings[2,])

knitr::kable(threeFL_split_row2) # cross-loading >.30, RED
```

```{r}
threeFL_split_row3 <- as.data.frame(threeFL_split_loadings[3,])

knitr::kable(threeFL_split_row3) # cross-loading >.30, RED
```

```{r}
threeFL_split_row4 <- as.data.frame(threeFL_split_loadings[4,])

knitr::kable(threeFL_split_row4) # no cross-loading >.30 but did not load >.4 on any factor, RED
```

```{r}
threeFL_split_row5 <- as.data.frame(threeFL_split_loadings[5,])

knitr::kable(threeFL_split_row5) # no cross-loading >.30 but did not load >.4 on any factor, RED
```

```{r}
threeFL_split_row6 <- as.data.frame(threeFL_split_loadings[6,])

knitr::kable(threeFL_split_row6) # cross-loading >.30, RED
```

```{r}
threeFL_split_row7 <- as.data.frame(threeFL_split_loadings[7,])

knitr::kable(threeFL_split_row7) # cross-loading >.30, RED
```

```{r}
threeFL_split_row8 <- as.data.frame(threeFL_split_loadings[8,])

knitr::kable(threeFL_split_row8) # cross-loading >.30, RED 
```

```{r}
threeFL_split_row9 <- as.data.frame(threeFL_split_loadings[9,])

knitr::kable(threeFL_split_row9) # cross-loading >.30, RED
```

```{r}
threeFL_split_row10 <- as.data.frame(threeFL_split_loadings[10,])

knitr::kable(threeFL_split_row10) # cross-loading >.30, RED 
```

```{r}
threeFL_split_row11 <- as.data.frame(threeFL_split_loadings[11,])

knitr::kable(threeFL_split_row11) # cross-loading >.30, RED
```

```{r}
threeFL_split_row12 <- as.data.frame(threeFL_split_loadings[12,])

knitr::kable(threeFL_split_row12) # cross-loading >.30, RED 
```

```{r}
threeFL_split_row13 <- as.data.frame(threeFL_split_loadings[13,])

knitr::kable(threeFL_split_row13) # cross-loading >.30, RED 
```

```{r}
threeFL_split_row14 <- as.data.frame(threeFL_split_loadings[14,])

knitr::kable(threeFL_split_row14) # cross-loading >.30, RED 
```

```{r}
threeFL_split_row15 <- as.data.frame(threeFL_split_loadings[15,])

knitr::kable(threeFL_split_row15) # cross-loading >.30, RED 
```

```{r}
threeFL_split_row16 <- as.data.frame(threeFL_split_loadings[16,])

knitr::kable(threeFL_split_row16) # cross-loading >.30, RED 
```

```{r}
threeFL_split_row17 <- as.data.frame(threeFL_split_loadings[17,])

knitr::kable(threeFL_split_row17) # cross-loading >.30, RED 
```

```{r}
threeFL_split_row18 <- as.data.frame(threeFL_split_loadings[18,])

knitr::kable(threeFL_split_row18) # cross-loading >.30, RED 
```

```{r}
threeFL_split_row19 <- as.data.frame(threeFL_split_loadings[19,])

knitr::kable(threeFL_split_row19) # cross-loading >.30, RED 
```

```{r}
threeFL_split_row20 <- as.data.frame(threeFL_split_loadings[20,])

knitr::kable(threeFL_split_row20) # loaded >.4 on two factors with cross-loading <.3, YELLOW
```

```{r}
threeFL_split_row21 <- as.data.frame(threeFL_split_loadings[21,])

knitr::kable(threeFL_split_row21) # cross-loading >.30, RED
```

```{r}
threeFL_split_row22 <- as.data.frame(threeFL_split_loadings[22,])

knitr::kable(threeFL_split_row22) # loaded >.4 on two factors with cross-loading <.3, YELLOW
```

```{r}
threeFL_split_row23 <- as.data.frame(threeFL_split_loadings[23,])

knitr::kable(threeFL_split_row23) # no cross-loading >.30 but did not load >.4 on any factor, RED
```

```{r}
threeFL_split_row24 <- as.data.frame(threeFL_split_loadings[24,])

knitr::kable(threeFL_split_row24) # cross-loading >.30, RED
```

```{r}
threeFL_split_row25 <- as.data.frame(threeFL_split_loadings[25,])

knitr::kable(threeFL_split_row25) # cross-loading >.30, RED
```

```{r}
threeFL_split_row26 <- as.data.frame(threeFL_split_loadings[26,])

knitr::kable(threeFL_split_row26) # loaded >.4 on two factors with cross-loading <.3, YELLOW
```

```{r}
threeFL_split_row27 <- as.data.frame(threeFL_split_loadings[27,])

knitr::kable(threeFL_split_row27) # cross-loading >.30, RED
```

```{r}
threeFL_split_row28 <- as.data.frame(threeFL_split_loadings[28,])

knitr::kable(threeFL_split_row28) # no cross-loading >.30 but did not load >.4 on any factor, RED
```

```{r}
threeFL_split_row29 <- as.data.frame(threeFL_split_loadings[29,])

knitr::kable(threeFL_split_row29) # cross-loading >.30, RED
```

```{r}
threeFL_split_row30 <- as.data.frame(threeFL_split_loadings[30,])

knitr::kable(threeFL_split_row30) # cross-loading >.30, RED
```

```{r}
threeFL_split_row31 <- as.data.frame(threeFL_split_loadings[31,])

knitr::kable(threeFL_split_row31) # cross-loading >.30, RED
```

```{r}
threeFL_split_row32 <- as.data.frame(threeFL_split_loadings[32,])

knitr::kable(threeFL_split_row32) # cross-loading >.30, RED
```

```{r}
threeFL_split_row33 <- as.data.frame(threeFL_split_loadings[33,])

knitr::kable(threeFL_split_row33) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
threeFL_split_row34 <- as.data.frame(threeFL_split_loadings[34,])

knitr::kable(threeFL_split_row34) # cross-loading >.30, RED
```

```{r}
threeFL_split_row35 <- as.data.frame(threeFL_split_loadings[35,])

knitr::kable(threeFL_split_row35) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
threeFL_split_row36 <- as.data.frame(threeFL_split_loadings[36,])

knitr::kable(threeFL_split_row36) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
threeFL_split_row37 <- as.data.frame(threeFL_split_loadings[37,])

knitr::kable(threeFL_split_row37) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
threeFL_split_row38 <- as.data.frame(threeFL_split_loadings[38,])

knitr::kable(threeFL_split_row38) # cross-loading >.30, RED
```

```{r}
# ========================================================================== YELLOW 3 START 

threeFL_YELLOW_split <- threeFL_split_df[c(20, 22, 26),]

threeFL_YELLOW_split_items <- threeFL_YELLOW_split$Item_No

# =========================================================================== YELLOW 3 END  

# ========================================================================== RED 6 START 

threeFL_RED_split <- threeFL_split_df[-c(20, 22, 26),]

threeFL_RED_split_items <- threeFL_RED_split$Item_No
# ========================================================================== RED 6 END 

### FOUR FACTOR LOADINGS 

fourFL_df <- which(FL_count == 4) # subsetting for items that loaded on four factors

fourFL_df <- Final_DF[fourFL_df, ]

tbl4 <- as.data.frame(table(fourFL_df$LoadedFactor))

knitr::kable(tbl4)
```

```{r}
fourFL_df_NoNum <- fourFL_df[,-c(1, 49)] # removing non-numerical columns

fourFL_df$firstloading <- apply(fourFL_df_NoNum, 1, function(z) na.omit(z)[1]) # extract first loading 

fourFL_df$firstloading <- as.numeric(fourFL_df$firstloading)

fourFL_df$secondloading <- apply(fourFL_df_NoNum, 1, function(z) na.omit(z)[2]) # extract second loading 

fourFL_df$secondloading <- as.numeric(fourFL_df$secondloading)

fourFL_df$thirdloading <- apply(fourFL_df_NoNum, 1, function(z) na.omit(z)[3]) # extract third loading 

fourFL_df$thirdloading <- as.numeric(fourFL_df$thirdloading)

fourFL_df$fourthloading <- apply(fourFL_df_NoNum, 1, function(z) na.omit(z)[4]) # extract fourth loading

fourFL_df$fourthloading <- as.numeric(fourFL_df$fourthloading)

fourFL_df$firstFL_inrange <- ifelse(abs(fourFL_df$firstloading) >= .40, TRUE, FALSE)

fourFL_df$secondFL_inrange <- ifelse(abs(fourFL_df$secondloading) >= .40, TRUE, FALSE)

fourFL_df$thirdFL_inrange <- ifelse(abs(fourFL_df$thirdloading) >= .40, TRUE, FALSE)

fourFL_df$fourthFL_inrange <- ifelse(abs(fourFL_df$fourthloading) >= .40, TRUE, FALSE)

fourFL_loadings <- fourFL_df[,49:57]
```

```{r}
fourFL_row1 <- as.data.frame(fourFL_loadings[1,])

knitr::kable(fourFL_row1) # cross-loading >.30, RED
```

```{r}
fourFL_row2 <- as.data.frame(fourFL_loadings[2,])

knitr::kable(fourFL_row2) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
fourFL_row3 <- as.data.frame(fourFL_loadings[3,])

knitr::kable(fourFL_row3) # cross-loading >.30, RED
```

```{r}
fourFL_row4 <- as.data.frame(fourFL_loadings[4,])

knitr::kable(fourFL_row4) # good in 3 samples, GREEN
```

```{r}
fourFL_row5 <- as.data.frame(fourFL_loadings[5,])

knitr::kable(fourFL_row5) # cross-loading >.30, RED
```

```{r}
fourFL_row6 <- as.data.frame(fourFL_loadings[6,])

knitr::kable(fourFL_row6) # cross-loading >.30, RED
```

```{r}
fourFL_row7 <- as.data.frame(fourFL_loadings[7,])

knitr::kable(fourFL_row7) # good in 3 samples, cross-loading <.3, GREEN
```

```{r}
fourFL_row8 <- as.data.frame(fourFL_loadings[8,])

knitr::kable(fourFL_row8) # good in 3 samples, GREEN
```

```{r}
fourFL_row9 <- as.data.frame(fourFL_loadings[9,])

knitr::kable(fourFL_row9) # cross-loading >.30, RED
```

```{r}
fourFL_row10 <- as.data.frame(fourFL_loadings[10,])

knitr::kable(fourFL_row10) # cross-loading >.30, RED
```

```{r}
fourFL_row11 <- as.data.frame(fourFL_loadings[11,])

knitr::kable(fourFL_row11) # cross-loading >.30, RED
```

```{r}
fourFL_row12 <- as.data.frame(fourFL_loadings[12,])

knitr::kable(fourFL_row12) # cross-loading >.30, RED
```

```{r}
fourFL_row13 <- as.data.frame(fourFL_loadings[13,])

knitr::kable(fourFL_row13) # cross-loading >.3, RED
```

```{r}
fourFL_row14 <- as.data.frame(fourFL_loadings[14,])

knitr::kable(fourFL_row14) # good in 3 samples, GREEN
```

```{r}
fourFL_row15 <- as.data.frame(fourFL_loadings[15,])

knitr::kable(fourFL_row15) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row16 <- as.data.frame(fourFL_loadings[16,])

knitr::kable(fourFL_row16) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row17 <- as.data.frame(fourFL_loadings[17,])

knitr::kable(fourFL_row17) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row18 <- as.data.frame(fourFL_loadings[18,])

knitr::kable(fourFL_row18) # cross-loading >.3, RED
```

```{r}
fourFL_row19 <- as.data.frame(fourFL_loadings[19,])

knitr::kable(fourFL_row19) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
fourFL_row20 <- as.data.frame(fourFL_loadings[20,])

knitr::kable(fourFL_row20) # cross-loading >.3, RED
```

```{r}
fourFL_row21 <- as.data.frame(fourFL_loadings[21,])

knitr::kable(fourFL_row21) # good in 3 samples, GREEN
```

```{r}
fourFL_row22 <- as.data.frame(fourFL_loadings[22,])

knitr::kable(fourFL_row22) # cross-loading >.3, RED
```

```{r}
fourFL_row23 <- as.data.frame(fourFL_loadings[23,])

knitr::kable(fourFL_row23) # good in 3 samples, GREEN
```

```{r}
fourFL_row24 <- as.data.frame(fourFL_loadings[24,])

knitr::kable(fourFL_row24) # cross-loading >.3, RED
```

```{r}
fourFL_row25 <- as.data.frame(fourFL_loadings[25,])

knitr::kable(fourFL_row25) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row26 <- as.data.frame(fourFL_loadings[26,])

knitr::kable(fourFL_row26) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row27 <- as.data.frame(fourFL_loadings[27,])

knitr::kable(fourFL_row27) # good in 2 samples, YELLOW
```

```{r}
fourFL_row28 <- as.data.frame(fourFL_loadings[28,])

knitr::kable(fourFL_row28) # cross-loading >.3, RED
```

```{r}
fourFL_row29 <- as.data.frame(fourFL_loadings[29,])

knitr::kable(fourFL_row29) # cross-loading >.3, RED
```

```{r}
fourFL_row30 <- as.data.frame(fourFL_loadings[30,])

knitr::kable(fourFL_row30) # cross-loading >.3, RED
```

```{r}
fourFL_row31 <- as.data.frame(fourFL_loadings[31,])

knitr::kable(fourFL_row31) # good in 3 samples, GREEN
```

```{r}
fourFL_row32 <- as.data.frame(fourFL_loadings[32,])

knitr::kable(fourFL_row32) # cross-loading >.3, RED
```

```{r}
fourFL_row33 <- as.data.frame(fourFL_loadings[33,])

knitr::kable(fourFL_row33) # cross-loading >.3, RED
```

```{r}
fourFL_row34 <- as.data.frame(fourFL_loadings[34,])

knitr::kable(fourFL_row34) # good in 3 samples & cross-loading <.3, GREEN 
```

```{r}
fourFL_row35 <- as.data.frame(fourFL_loadings[35,])

knitr::kable(fourFL_row35) # good in 3 samples, GREEN
```

```{r}
fourFL_row36 <- as.data.frame(fourFL_loadings[36,])

knitr::kable(fourFL_row36) # good in 3 samples, GREEN
```

```{r}
fourFL_row37 <- as.data.frame(fourFL_loadings[37,])

knitr::kable(fourFL_row37) # cross-loading >.3, RED
```

```{r}
fourFL_row38 <- as.data.frame(fourFL_loadings[38,])

knitr::kable(fourFL_row38) # cross-loading >.3, RED
```

```{r}
fourFL_row39 <- as.data.frame(fourFL_loadings[39,])

knitr::kable(fourFL_row39) # cross-loading >.3, RED
```

```{r}
fourFL_row40 <- as.data.frame(fourFL_loadings[40,])

knitr::kable(fourFL_row40) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row41 <- as.data.frame(fourFL_loadings[41,])

knitr::kable(fourFL_row41) # cross-loading >.3, RED
```

```{r}
fourFL_row42 <- as.data.frame(fourFL_loadings[42,])

knitr::kable(fourFL_row42) # cross-loading >.3, RED
```

```{r}
fourFL_row43 <- as.data.frame(fourFL_loadings[43,])

knitr::kable(fourFL_row43) # cross-loading >.3, RED
```

```{r}
fourFL_row44 <- as.data.frame(fourFL_loadings[44,])

knitr::kable(fourFL_row44) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row45 <- as.data.frame(fourFL_loadings[45,])

knitr::kable(fourFL_row45) # good in 3 samples, GREEN
```

```{r}
fourFL_row46 <- as.data.frame(fourFL_loadings[46,])

knitr::kable(fourFL_row46) # good in 2 samples, cross-loading <.3, YELLOW
```

```{r}
fourFL_row47 <- as.data.frame(fourFL_loadings[47,])

knitr::kable(fourFL_row47) # cross-loading >.3, RED
```

```{r}
fourFL_row48 <- as.data.frame(fourFL_loadings[48,])

knitr::kable(fourFL_row48) # cross-loading >.3, RED
```

```{r}
fourFL_row49 <- as.data.frame(fourFL_loadings[49,])

knitr::kable(fourFL_row49) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
fourFL_row50 <- as.data.frame(fourFL_loadings[50,])

knitr::kable(fourFL_row50) # cross-loading >.3, RED
```

```{r}
fourFL_row51 <- as.data.frame(fourFL_loadings[51,])

knitr::kable(fourFL_row51) # cross-loading >.3, RED
```

```{r}
fourFL_row52 <- as.data.frame(fourFL_loadings[52,])

knitr::kable(fourFL_row52) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
fourFL_row53 <- as.data.frame(fourFL_loadings[53,])

knitr::kable(fourFL_row53) # cross-loading >.3, RED
```

```{r}
fourFL_row54 <- as.data.frame(fourFL_loadings[54,])

knitr::kable(fourFL_row54) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row55 <- as.data.frame(fourFL_loadings[55,])

knitr::kable(fourFL_row55) # good in 3 samples, GREEN
```

```{r}
fourFL_row56 <- as.data.frame(fourFL_loadings[56,])

knitr::kable(fourFL_row56) # cross-loading >.3, RED
```

```{r}
fourFL_row57 <- as.data.frame(fourFL_loadings[57,])

knitr::kable(fourFL_row57) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row58 <- as.data.frame(fourFL_loadings[58,])

knitr::kable(fourFL_row58) # cross-loading >.3, RED
```

```{r}
fourFL_row59 <- as.data.frame(fourFL_loadings[59,])

knitr::kable(fourFL_row59) # cross-loading >.3, RED
```

```{r}
fourFL_row60 <- as.data.frame(fourFL_loadings[60,])

knitr::kable(fourFL_row60) # cross-loading >.3, RED
```

```{r}
fourFL_row61 <- as.data.frame(fourFL_loadings[61,])

knitr::kable(fourFL_row61) # cross-loading >.3, RED
```

```{r}
fourFL_row62 <- as.data.frame(fourFL_loadings[62,])

knitr::kable(fourFL_row62) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row63 <- as.data.frame(fourFL_loadings[63,])

knitr::kable(fourFL_row63) # cross-loading >.3, RED
```

```{r}
fourFL_row64 <- as.data.frame(fourFL_loadings[64,])

knitr::kable(fourFL_row64) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row65 <- as.data.frame(fourFL_loadings[65,])

knitr::kable(fourFL_row65) # cross-loading >.3, RED
```

```{r}
fourFL_row66 <- as.data.frame(fourFL_loadings[66,])

knitr::kable(fourFL_row66) # cross-loading >.3, RED
```

```{r}
fourFL_row67 <- as.data.frame(fourFL_loadings[67,])

knitr::kable(fourFL_row67) # good in 3 samples, GREEN
```

```{r}
fourFL_row68 <- as.data.frame(fourFL_loadings[68,])

knitr::kable(fourFL_row68) # cross-loading >.3, RED
```

```{r}
fourFL_row69 <- as.data.frame(fourFL_loadings[69,])

knitr::kable(fourFL_row69) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row70 <- as.data.frame(fourFL_loadings[70,])

knitr::kable(fourFL_row70) # cross-loading >.3, RED
```

```{r}
fourFL_row71 <- as.data.frame(fourFL_loadings[71,])

knitr::kable(fourFL_row71) # cross-loading >.3, RED
```

```{r}
fourFL_row72 <- as.data.frame(fourFL_loadings[72,])

knitr::kable(fourFL_row72) # cross-loading >.3, RED
```

```{r}
fourFL_row73 <- as.data.frame(fourFL_loadings[73,])

knitr::kable(fourFL_row73) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row74 <- as.data.frame(fourFL_loadings[74,])

knitr::kable(fourFL_row74) # cross-loading >.3, RED
```

```{r}
fourFL_row75 <- as.data.frame(fourFL_loadings[75,])

knitr::kable(fourFL_row75) # no loadings >.4, RED
```

```{r}
fourFL_row76 <- as.data.frame(fourFL_loadings[76,])

knitr::kable(fourFL_row76) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row77 <- as.data.frame(fourFL_loadings[77,])

knitr::kable(fourFL_row77) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row78 <- as.data.frame(fourFL_loadings[78,])

knitr::kable(fourFL_row78) # cross-loading >.3, RED
```

```{r}
fourFL_row79<- as.data.frame(fourFL_loadings[79,])

knitr::kable(fourFL_row79) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row80 <- as.data.frame(fourFL_loadings[80,])

knitr::kable(fourFL_row80) # good in 2 samples, YELLOW
```

```{r}
fourFL_row81 <- as.data.frame(fourFL_loadings[81,])

knitr::kable(fourFL_row81) # cross-loading >.3, RED
```

```{r}
fourFL_row82 <- as.data.frame(fourFL_loadings[82,])

knitr::kable(fourFL_row82) # good in 3 samples, GREEN
```

```{r}
fourFL_row83 <- as.data.frame(fourFL_loadings[83,])

knitr::kable(fourFL_row83) # cross-loading >.3, RED
```

```{r}
fourFL_row84 <- as.data.frame(fourFL_loadings[84,])

knitr::kable(fourFL_row84) # cross-loading >.3, RED
```

```{r}
fourFL_row85 <- as.data.frame(fourFL_loadings[85,])

knitr::kable(fourFL_row85) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row86 <- as.data.frame(fourFL_loadings[86,])

knitr::kable(fourFL_row86) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fourFL_row87 <- as.data.frame(fourFL_loadings[87,])

knitr::kable(fourFL_row87) # cross-loading >.3, RED
```

```{r}
fourFL_row88 <- as.data.frame(fourFL_loadings[88,])

knitr::kable(fourFL_row88) # cross-loading >.3, RED
```

```{r}
fourFL_row89 <- as.data.frame(fourFL_loadings[89,])

knitr::kable(fourFL_row89) # cross-loading >.3, RED
```

```{r}
fourFL_row90 <- as.data.frame(fourFL_loadings[90,])

knitr::kable(fourFL_row90) # cross-loading >.3, RED
```

```{r}
fourFL_row91 <- as.data.frame(fourFL_loadings[91,])

knitr::kable(fourFL_row91) # cross-loading >.3, RED
```

```{r}
fourFL_row92 <- as.data.frame(fourFL_loadings[92,])

knitr::kable(fourFL_row92) # cross-loading >.3, RED
```

```{r}
fourFL_row93 <- as.data.frame(fourFL_loadings[93,])

knitr::kable(fourFL_row93) # cross-loading >.3, RED
```

```{r}
fourFL_row94 <- as.data.frame(fourFL_loadings[94,])

knitr::kable(fourFL_row94) # cross-loading >.3, RED
```

```{r}
# ========================================================================== GREEN 2 START 

fourFL_GREEN <- fourFL_df[c(4, 7, 8, 14, 15, 16, 17, 21, 23, 25, 26, 31, 34, 35, 36, 40, 44, 45, 54, 55, 57, 62, 64, 67, 69, 73, 76, 77, 79, 82, 85, 86),]

fourFL_GREEN_items <- fourFL_GREEN$Item_No

# ========================================================================== GREEN 2 END

# ========================================================================== YELLOW 4 START 

fourFL_YELLOW <- fourFL_df[c(27, 46, 80),]

fourFL_YELLOW_items <- fourFL_YELLOW$Item_No

# =========================================================================== YELLOW 4 END  

# ========================================================================== RED 7 START 

fourFL_RED <- fourFL_df[c(1, 2, 3, 5, 6, 9, 10, 11, 12, 13, 18, 19, 20, 22, 24, 28, 29, 30, 
32, 33, 37, 38, 39, 41, 42, 43, 47, 48, 49, 50, 51, 52, 53, 56, 58, 59, 60, 61, 63, 65, 66, 68, 70, 71, 72, 74, 75, 78, 81, 83, 84, 87, 88, 89, 90, 91, 92, 93, 94),]

fourFL_RED_items <- fourFL_RED$Item_No
# ========================================================================== RED 7 END 

### FIVE FACTOR LOADINGS 

fiveFL_df <- which(FL_count == 5) # subsetting for items that loaded on five factors

fiveFL_df <- Final_DF[fiveFL_df, ]

tbl5 <- as.data.frame(table(fiveFL_df$LoadedFactor))

knitr::kable(tbl5)
```

```{r}
fiveFL_df_NoNum <- fiveFL_df[,-c(1, 49)] # removing non-numerical columns

fiveFL_df$firstloading <- apply(fiveFL_df_NoNum, 1, function(z) na.omit(z)[1]) # extract first loading 

fiveFL_df$firstloading <- as.numeric(fiveFL_df$firstloading)

fiveFL_df$secondloading <- apply(fiveFL_df_NoNum, 1, function(z) na.omit(z)[2]) # extract second loading 

fiveFL_df$secondloading <- as.numeric(fiveFL_df$secondloading)

fiveFL_df$thirdloading <- apply(fiveFL_df_NoNum, 1, function(z) na.omit(z)[3]) # extract third loading 

fiveFL_df$thirdloading <- as.numeric(fiveFL_df$thirdloading)

fiveFL_df$fourthloading <- apply(fiveFL_df_NoNum, 1, function(z) na.omit(z)[4]) # extract fiveth loading

fiveFL_df$fourthloading <- as.numeric(fiveFL_df$fourthloading)

fiveFL_df$fifthloading <- apply(fiveFL_df_NoNum, 1, function(z) na.omit(z)[5]) # extract fiveth loading

fiveFL_df$fifthloading <- as.numeric(fiveFL_df$fifthloading)

fiveFL_df$firstFL_inrange <- ifelse(abs(fiveFL_df$firstloading) >= .40, TRUE, FALSE)

fiveFL_df$secondFL_inrange <- ifelse(abs(fiveFL_df$secondloading) >= .40, TRUE, FALSE)

fiveFL_df$thirdFL_inrange <- ifelse(abs(fiveFL_df$thirdloading) >= .40, TRUE, FALSE)

fiveFL_df$fourthFL_inrange <- ifelse(abs(fiveFL_df$fourthloading) >= .40, TRUE, FALSE)

fiveFL_df$fifthFL_inrange <- ifelse(abs(fiveFL_df$fifthloading) >= .40, TRUE, FALSE)

fiveFL_loadings <- fiveFL_df[,49:59]
```

```{r}
fiveFL_row1 <- as.data.frame(fiveFL_loadings[1,])

knitr::kable(fiveFL_row1) # cross-loading >.3, RED
```

```{r}
fiveFL_row2 <- as.data.frame(fiveFL_loadings[2,])

knitr::kable(fiveFL_row2) # cross-loading >.3, RED
```

```{r}
fiveFL_row3 <- as.data.frame(fiveFL_loadings[3,])

knitr::kable(fiveFL_row3) # cross-loading >.3, RED
```

```{r}
fiveFL_row4 <- as.data.frame(fiveFL_loadings[4,])

knitr::kable(fiveFL_row4) # cross-loading >.3, RED 
```

```{r}
fiveFL_row5 <- as.data.frame(fiveFL_loadings[5,])

knitr::kable(fiveFL_row5) # cross-loading >.3, RED
```

```{r}
fiveFL_row6 <- as.data.frame(fiveFL_loadings[6,])

knitr::kable(fiveFL_row6) # cross-loading >.3, RED
```

```{r}
fiveFL_row7 <- as.data.frame(fiveFL_loadings[7,])

knitr::kable(fiveFL_row7) # cross-loading >.3, RED
```

```{r}
fiveFL_row8 <- as.data.frame(fiveFL_loadings[8,])

knitr::kable(fiveFL_row8) # cross-loading >.3, RED
```

```{r}
fiveFL_row9 <- as.data.frame(fiveFL_loadings[9,])

knitr::kable(fiveFL_row9) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
fiveFL_row10 <- as.data.frame(fiveFL_loadings[10,])

knitr::kable(fiveFL_row10) # cross-loading >.3, RED
```

```{r}
fiveFL_row11 <- as.data.frame(fiveFL_loadings[11,])

knitr::kable(fiveFL_row11) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fiveFL_row12 <- as.data.frame(fiveFL_loadings[12,])

knitr::kable(fiveFL_row12) # cross-loading >.3, RED
```

```{r}
fiveFL_row13 <- as.data.frame(fiveFL_loadings[13,])

knitr::kable(fiveFL_row13) # cross-loading >.3, RED
```

```{r}
fiveFL_row14 <- as.data.frame(fiveFL_loadings[14,])

knitr::kable(fiveFL_row14) # cross-loading >.3, RED
```

```{r}
fiveFL_row15 <- as.data.frame(fiveFL_loadings[15,])

knitr::kable(fiveFL_row15) # cross-loading >.3, RED
```

```{r}
fiveFL_row16 <- as.data.frame(fiveFL_loadings[16,])

knitr::kable(fiveFL_row16) # cross-loading >.3, RED
```

```{r}
fiveFL_row17 <- as.data.frame(fiveFL_loadings[17,])

knitr::kable(fiveFL_row17) # cross-loading >.3, RED
```

```{r}
fiveFL_row18 <- as.data.frame(fiveFL_loadings[18,])

knitr::kable(fiveFL_row18) # cross-loading >.3, RED
```

```{r}
fiveFL_row19 <- as.data.frame(fiveFL_loadings[19,])

knitr::kable(fiveFL_row19) # cross-loading >.3, RED
```

```{r}
fiveFL_row20 <- as.data.frame(fiveFL_loadings[20,])

knitr::kable(fiveFL_row20) # cross-loading >.3, RED
```

```{r}
fiveFL_row21 <- as.data.frame(fiveFL_loadings[21,])

knitr::kable(fiveFL_row21) # cross-loading >.3, RED
```

```{r}
fiveFL_row22 <- as.data.frame(fiveFL_loadings[22,])

knitr::kable(fiveFL_row22) # cross-loading >.3, RED
```

```{r}
fiveFL_row23 <- as.data.frame(fiveFL_loadings[23,])

knitr::kable(fiveFL_row23) # cross-loading >.3, RED
```

```{r}
fiveFL_row24 <- as.data.frame(fiveFL_loadings[24,])

knitr::kable(fiveFL_row24) # cross-loading >.3, RED
```

```{r}
fiveFL_row25 <- as.data.frame(fiveFL_loadings[25,])

knitr::kable(fiveFL_row25) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
fiveFL_row26 <- as.data.frame(fiveFL_loadings[26,])

knitr::kable(fiveFL_row26) # no cross-loading >.30 but only loaded >.4 in one sample, RED
```

```{r}
fiveFL_row27 <- as.data.frame(fiveFL_loadings[27,])

knitr::kable(fiveFL_row27) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fiveFL_row28 <- as.data.frame(fiveFL_loadings[28,])

knitr::kable(fiveFL_row28) # cross-loading >.3, RED
```

```{r}
fiveFL_row29 <- as.data.frame(fiveFL_loadings[29,])

knitr::kable(fiveFL_row29) # good in 2 samples, no cross-loadings >.3, YELLOW
```

```{r}
fiveFL_row30 <- as.data.frame(fiveFL_loadings[30,])

knitr::kable(fiveFL_row30) # cross-loading >.3, RED
```

```{r}
fiveFL_row31 <- as.data.frame(fiveFL_loadings[31,])

knitr::kable(fiveFL_row31) # cross-loading >.3, RED
```

```{r}
fiveFL_row32 <- as.data.frame(fiveFL_loadings[32,])

knitr::kable(fiveFL_row32) # cross-loading >.3, RED
```

```{r}
fiveFL_row33 <- as.data.frame(fiveFL_loadings[33,])

knitr::kable(fiveFL_row33) # cross-loading >.3, RED
```

```{r}
fiveFL_row34 <- as.data.frame(fiveFL_loadings[34,])

knitr::kable(fiveFL_row34) # no cross-loading >.30 but did not load >.4 in any sample, RED
```

```{r}
fiveFL_row35 <- as.data.frame(fiveFL_loadings[35,])

knitr::kable(fiveFL_row35) # cross-loading >.3, RED
```

```{r}
fiveFL_row36 <- as.data.frame(fiveFL_loadings[36,])

knitr::kable(fiveFL_row36) # cross-loading >.3, RED
```

```{r}
fiveFL_row37 <- as.data.frame(fiveFL_loadings[37,])

knitr::kable(fiveFL_row37) # cross-loading >.3, RED
```

```{r}
fiveFL_row38 <- as.data.frame(fiveFL_loadings[38,])

knitr::kable(fiveFL_row38) # good in 3 samples & cross-loadings <.3, GREEN
```

```{r}
fiveFL_row39 <- as.data.frame(fiveFL_loadings[39,])

knitr::kable(fiveFL_row39) # cross-loading >.3, RED
```

```{r}
fiveFL_row40 <- as.data.frame(fiveFL_loadings[40,])

knitr::kable(fiveFL_row40) # cross-loading >.3, RED
```

```{r}
fiveFL_row41 <- as.data.frame(fiveFL_loadings[41,])

knitr::kable(fiveFL_row41) # cross-loading >.3, RED
```

```{r}
fiveFL_row42 <- as.data.frame(fiveFL_loadings[42,])

knitr::kable(fiveFL_row42) # cross-loading >.3, RED
```

```{r}
fiveFL_row43 <- as.data.frame(fiveFL_loadings[43,])

knitr::kable(fiveFL_row43) # cross-loading >.3, RED
```

```{r}
fiveFL_row44 <- as.data.frame(fiveFL_loadings[44,])

knitr::kable(fiveFL_row44) # cross-loading >.3, RED
```

```{r}
fiveFL_row45 <- as.data.frame(fiveFL_loadings[45,])

knitr::kable(fiveFL_row45) # cross-loading >.3, RED
```

```{r}
fiveFL_row46 <- as.data.frame(fiveFL_loadings[46,])

knitr::kable(fiveFL_row46) # cross-loading >.3, RED
```

```{r}
fiveFL_row47 <- as.data.frame(fiveFL_loadings[47,])

knitr::kable(fiveFL_row47) # cross-loading >.3, RED
```

```{r}
fiveFL_row48 <- as.data.frame(fiveFL_loadings[48,])

knitr::kable(fiveFL_row48) # cross-loading >.3, RED
```

```{r}
fiveFL_row49 <- as.data.frame(fiveFL_loadings[49,])

knitr::kable(fiveFL_row49) # good in 2 samples, no cross-loading >.3, YELLOW
```

```{r}
fiveFL_row50 <- as.data.frame(fiveFL_loadings[50,])

knitr::kable(fiveFL_row50) # cross-loading >.3, RED
```

```{r}
fiveFL_row51 <- as.data.frame(fiveFL_loadings[51,])

knitr::kable(fiveFL_row51) # cross-loading >.3, RED
```

```{r}
fiveFL_row52 <- as.data.frame(fiveFL_loadings[52,])

knitr::kable(fiveFL_row52) # cross-loading >.3, RED
```

```{r}
fiveFL_row53 <- as.data.frame(fiveFL_loadings[53,])

knitr::kable(fiveFL_row53) # cross-loading >.3, RED
```

```{r}
fiveFL_row54 <- as.data.frame(fiveFL_loadings[54,])

knitr::kable(fiveFL_row54) # cross-loading >.3, RED
```

```{r}
fiveFL_row55 <- as.data.frame(fiveFL_loadings[55,])

knitr::kable(fiveFL_row55) # cross-loading >.3, RED
```

```{r}
fiveFL_row56 <- as.data.frame(fiveFL_loadings[56,])

knitr::kable(fiveFL_row56) # cross-loading >.3, RED
```

```{r}
fiveFL_row57 <- as.data.frame(fiveFL_loadings[57,])

knitr::kable(fiveFL_row57) # cross-loading >.3, RED
```

```{r}
fiveFL_row58 <- as.data.frame(fiveFL_loadings[58,])

knitr::kable(fiveFL_row58) # cross-loading >.3, RED
```

```{r}
fiveFL_row59 <- as.data.frame(fiveFL_loadings[59,])

knitr::kable(fiveFL_row59) # good in 3 samples, GREEN
```

```{r}
fiveFL_row60 <- as.data.frame(fiveFL_loadings[60,])

knitr::kable(fiveFL_row60) # cross-loading >.3, RED
```

```{r}
fiveFL_row61 <- as.data.frame(fiveFL_loadings[61,])

knitr::kable(fiveFL_row61) # cross-loading >.3, RED
```

```{r}
fiveFL_row62 <- as.data.frame(fiveFL_loadings[62,])

knitr::kable(fiveFL_row62) # cross-loading >.3, RED 
```

```{r}
fiveFL_row63 <- as.data.frame(fiveFL_loadings[63,])

knitr::kable(fiveFL_row63) # cross-loading >.3, RED
```

```{r}
fiveFL_row64 <- as.data.frame(fiveFL_loadings[64,])

knitr::kable(fiveFL_row64) # good in 3 samples & cross-loading <.3, GREEN
```

```{r}
fiveFL_row65 <- as.data.frame(fiveFL_loadings[65,])

knitr::kable(fiveFL_row65) # cross-loading >.3, RED
```

```{r}
# ========================================================================== GREEN 3 START 

fiveFL_GREEN <- fiveFL_df[c(11, 27, 38, 59, 64),]

fiveFL_GREEN_items <- fiveFL_GREEN$Item_No

# ========================================================================== GREEN 3 END

# ========================================================================== YELLOW 5 START 

fiveFL_YELLOW <- fiveFL_df[c(29, 49),]

fiveFL_YELLOW_items <- fiveFL_YELLOW$Item_No

# =========================================================================== YELLOW 5 END  

# ========================================================================== RED 8 START 

fiveFL_RED <- fiveFL_df[-c(11, 27, 29, 38, 49, 59, 64),]

fiveFL_RED_items <- fiveFL_RED$Item_No
# ========================================================================== RED 8 END 

### SIX FACTOR LOADINGS 

sixFL_df <- which(FL_count == 6) # subsetting for items that loaded on six factors

sixFL_df <- Final_DF[sixFL_df, ]

tbl6 <- as.data.frame(table(sixFL_df$LoadedFactor))

knitr::kable(tbl6)
```

```{r}
sixFL_df_NoNum <- sixFL_df[,-c(1, 49)] # removing non-numerical columns

sixFL_df$firstloading <- apply(sixFL_df_NoNum, 1, function(z) na.omit(z)[1]) # extract first loading 

sixFL_df$firstloading <- as.numeric(sixFL_df$firstloading)

sixFL_df$secondloading <- apply(sixFL_df_NoNum, 1, function(z) na.omit(z)[2]) # extract second loading 

sixFL_df$secondloading <- as.numeric(sixFL_df$secondloading)

sixFL_df$thirdloading <- apply(sixFL_df_NoNum, 1, function(z) na.omit(z)[3]) # extract third loading 

sixFL_df$thirdloading <- as.numeric(sixFL_df$thirdloading)

sixFL_df$fourthloading <- apply(sixFL_df_NoNum, 1, function(z) na.omit(z)[4]) # extract sixth loading

sixFL_df$fourthloading <- as.numeric(sixFL_df$fourthloading)

sixFL_df$fifthloading <- apply(sixFL_df_NoNum, 1, function(z) na.omit(z)[5]) # extract fifth loading

sixFL_df$fifthloading <- as.numeric(sixFL_df$fifthloading)

sixFL_df$firstFL_inrange <- ifelse(abs(sixFL_df$firstloading) >= .40, TRUE, FALSE)

sixFL_df$secondFL_inrange <- ifelse(abs(sixFL_df$secondloading) >= .40, TRUE, FALSE)

sixFL_df$thirdFL_inrange <- ifelse(abs(sixFL_df$thirdloading) >= .40, TRUE, FALSE)

sixFL_df$fourthFL_inrange <- ifelse(abs(sixFL_df$fourthloading) >= .40, TRUE, FALSE)

sixFL_df$fifthFL_inrange <- ifelse(abs(sixFL_df$fifthloading) >= .40, TRUE, FALSE)



sixFL_loadings <- sixFL_df[,49:59]
```
